apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-configure-clusterlevel-rbac
  namespace: default
  annotations:
    policy.open-cluster-management.io/description: policy-configure-clusterlevel-rbac
  creationTimestamp: 2023-09-15T19:17:11Z
  generation: 2
  managedFields:
  resourceVersion: "68760428"
  uid: c442a489-a5eb-424a-ad0d-bdde5e2a67f1
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-configure-clusterlevel
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: cluster-admin-0
                roleRef:
                  name: cluster-admin
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                subjects:
                  - name: devadmin
                    apiGroup: rbac.authorization.k8s.io
                    kind: User
