apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-remove-kubadmin
  namespace: default
  annotations:
    policy.open-cluster-management.io/description: policy-remove-kubadmin
  creationTimestamp: 2023-09-15T19:36:27Z
  generation: 1
  managedFields:
  resourceVersion: "68782003"
  uid: 60c8bf74-94f5-4659-b0ba-d73c89292ad6
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-remove-kubeadmin
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: kubeadmin
                  namespace: kube-system
                type: Opaque
